import { TYPES } from './variables'

export function getPokemonBgColor(type) {
  if (type === undefined) return '[#68A090]'
  if (type === TYPES.NORMAL) return 'bg-gray-700'
  if (type === TYPES.FIGHTING) return 'bg-red-600'
  if (type === TYPES.FLYING) return 'bg-blue-300'
  if (type === TYPES.POISON) return 'bg-purple-600'
  if (type === TYPES.GROUND) return 'bg-yellow-500'
  if (type === TYPES.ROCK) return 'bg-yellow-700'
  if (type === TYPES.BUG) return 'bg-green-600'
  if (type === TYPES.GHOST) return 'bg-purple-800'
  if (type === TYPES.STEEL) return 'bg-gray-500'
  if (type === TYPES.FIRE) return 'bg-red-500'
  if (type === TYPES.WATER) return 'bg-blue-500'
  if (type === TYPES.GRASS) return 'bg-green-500'
  if (type === TYPES.ELECTRIC) return 'bg-yellow-300'
  if (type === TYPES.PSYCHIC) return 'bg-pink-500'
  if (type === TYPES.ICE) return 'bg-blue-200'
  if (type === TYPES.DRAGON) return 'bg-purple-400'
  if (type === TYPES.DARK) return 'bg-gray-800'
  if (type === TYPES.FAIRY) return 'bg-pink-300'
  if (type === TYPES.UNKNOWN) return 'bg-gray-400'
  if (type === TYPES.SHADOW) return 'bg-gray-700'
}

export function getPokemonTxtColor(type) {
  if (type === undefined) return '[#68A090]'
  if (type === TYPES.NORMAL) return 'text-gray-700'
  if (type === TYPES.FIGHTING) return 'text-red-600'
  if (type === TYPES.FLYING) return 'text-blue-300'
  if (type === TYPES.POISON) return 'text-purple-600'
  if (type === TYPES.GROUND) return 'text-yellow-500'
  if (type === TYPES.ROCK) return 'text-yellow-700'
  if (type === TYPES.BUG) return 'text-green-600'
  if (type === TYPES.GHOST) return 'text-purple-800'
  if (type === TYPES.STEEL) return 'text-gray-500'
  if (type === TYPES.FIRE) return 'text-red-500'
  if (type === TYPES.WATER) return 'text-blue-500'
  if (type === TYPES.GRASS) return 'text-green-500'
  if (type === TYPES.ELECTRIC) return 'text-yellow-300'
  if (type === TYPES.PSYCHIC) return 'text-pink-500'
  if (type === TYPES.ICE) return 'text-blue-200'
  if (type === TYPES.DRAGON) return 'text-purple-400'
  if (type === TYPES.DARK) return 'text-gray-800'
  if (type === TYPES.FAIRY) return 'text-pink-300'
  if (type === TYPES.UNKNOWN) return 'text-gray-400'
  if (type === TYPES.SHADOW) return 'text-gray-700'
}
